import logging
from utils.llm_client import query_llm


# ── Task 5: Entity data summariser ────────────────────────────────────────────

def _build_entity_summary(graph) -> str:
    """
    Pull the richest entity-level data from the graph for the LLM prompt.

    Returns two sections:
      KEY ESG METRICS  — high-confidence ESG Metric nodes
      KEY DATA POINTS  — Quantitative Value nodes with context snippets
    """
    metrics = []
    quant   = []
    company_name = None

    for n, d in graph.nodes(data=True):
        label = d.get("label", "")
        text  = d.get("text", "").strip()
        score = d.get("score", 0.0)
        ctx   = d.get("context", "")

        # Capture primary company name (highest-scored Company node)
        if label == "Company" and score > 0.9:
            if company_name is None or score > 0.95:
                company_name = text

        # ESG Metric nodes
        if label == "ESG Metric" and text and score >= 0.6:
            metrics.append((score, text))

        # Quantitative Value nodes with context (most informative)
        if label == "Quantitative Value" and text and ctx:
            snippet = ctx[:140].replace("\n", " ").strip()
            quant.append((score, f"{text} — {snippet}"))

    # Sort by score descending, deduplicate by text
    metrics = sorted(set(t for _, t in sorted(metrics, reverse=True)[:20]))
    quant   = [line for _, line in sorted(quant, reverse=True)[:18]]

    lines = []
    if metrics:
        lines.append("KEY ESG METRICS IDENTIFIED:")
        lines.extend(f"  - {m}" for m in metrics)
    if quant:
        lines.append("KEY QUANTITATIVE DATA POINTS:")
        lines.extend(f"  - {q}" for q in quant)

    return "\n".join(lines) if lines else ""


def _extract_typed_nodes(graph) -> tuple[str, str, str]:
    """Extract observations, targets, and events as formatted strings."""
    observations, targets, events = [], [], []

    for n, d in graph.nodes(data=True):
        node_type = d.get("type", "")
        text      = d.get("text", "").strip()
        year      = d.get("year", "")

        if node_type == "observation":
            val  = d.get("value", "")
            unit = d.get("unit", "")
            if val and val.lower() not in ("none", "unknown", ""):
                observations.append(
                    f"  - {text} (value: {val} {unit}, year: {year})".rstrip()
                )

        elif node_type == "target":
            ttype = d.get("target_type", "")
            observations.append(f"  - Target: {ttype} by {year}")
            targets.append(f"  - {ttype} by {year}")

        elif node_type == "event":
            metric     = d.get("metric", "")
            value      = d.get("value", "")
            unit       = d.get("unit", "")
            event_type = d.get("event_type", "")
            if value and value.lower() not in ("none", "unknown", ""):
                events.append(
                    f"  - {event_type}: {metric} = {value} {unit} ({year})".rstrip()
                )

    obs_str    = "\n".join(observations[:15]) or "  (none extracted)"
    target_str = "\n".join(targets[:10])      or "  (none extracted)"
    event_str  = "\n".join(events[:12])       or "  (none extracted)"
    return obs_str, target_str, event_str


def _detect_main_company(graph) -> str:
    """Return the name of the highest-confidence Company node."""
    best_score = 0.0
    best_name  = "the company"
    for _, d in graph.nodes(data=True):
        if d.get("label") == "Company":
            s = d.get("score", 0.0)
            if s > best_score:
                best_score = s
                best_name  = d.get("text", best_name)
    return best_name


def generate_narrative(graph, topics, quant_qual):
    """
    Generate a professional ESG narrative summary from the V2 Knowledge Graph.

    Task 5 improvements:
      - Feeds entity-level data (metrics + quantitative values) into the prompt
      - Identifies and names the main company explicitly
      - Falls back to a structured markdown summary if LLM is unavailable
    """
    logging.info("Generating V2 narrative summary with enriched entity context")

    company_name  = _detect_main_company(graph)
    entity_block  = _build_entity_summary(graph)
    obs_str, target_str, event_str = _extract_typed_nodes(graph)

    prompt = f"""[INST] <<SYS>>
You are a senior ESG analyst writing a professional investor-grade narrative for a company's annual sustainability report.

STRICT RULES:
- Output ONLY the narrative text. No labels, no headers, no meta-commentary.
- DO NOT include "Narrative Summary:", "Response:", "Summary:", or any similar prefix.
- DO NOT write "Generated by" or sign the response.
- Name the company explicitly — do not write "the company" if the name is known.
- Only compare metrics that refer to the same subject across years.
- Include specific numbers, percentages, and targets from the data provided.
- Structure: Environmental performance → Social/Workforce → Governance → Outlook.
<</SYS>>

COMPANY: {company_name}

TOPIC CLASSIFICATION SCORES (E/S/G):
{topics}

{entity_block}

STRUCTURED OBSERVATIONS:
{obs_str}

COMMITMENTS & TARGETS:
{target_str}

KEY EVENTS (CHANGES):
{event_str}

NARRATIVE:
[/INST]"""

    response = query_llm(prompt)

    if not response:
        # ── Structured fallback (no LLM available) ────────────────────────────
        logging.warning("LLM unavailable — generating structured fallback narrative")
        return _structured_fallback(company_name, entity_block, obs_str, target_str, event_str, topics)

    # ── Clean up common LLM artefacts ─────────────────────────────────────────
    clean = response.strip()
    for marker in [
        "Response:", "NARRATIVE SUMMARY:", "Narrative Summary:",
        "Summary:", "NAME_1", "NARRATIVE:", "[/INST]",
    ]:
        if clean.startswith(marker):
            clean = clean[len(marker):].strip()

    if "Generated by me" in clean:
        clean = clean.split("Generated by me")[0].strip()

    return clean


def _structured_fallback(company, entity_block, obs, targets, events, topics) -> str:
    """Rich markdown fallback when the LLM server is unreachable."""
    lines = [
        f"# ESG Disclosure Summary — {company}\n",
        f"**ESG Topic Coverage:** {topics}\n",
    ]
    if entity_block:
        lines.append(f"## Key Metrics & Data Points\n{entity_block}\n")
    lines.append(f"## Structured Observations\n{obs}\n")
    lines.append(f"## Commitments & Targets\n{targets}\n")
    lines.append(f"## Key Events\n{events}\n")
    return "\n".join(lines)
